### ISSUE TITLE
locations() and IHD surface

### ISSUE THREAD

**Issue by dke-chan** [b-steve/ascr#13]
I've started some work to allow **ascr**'s `location()` function to recalculate the IHD surface ([Commit A](https://github.com/dke-chan/ascr/commit/8d876719fc3014b063af09e986c3d61fa61bec0d), [Commit B](https://github.com/dke-chan/ascr/commit/1419cb8ea858ba5b35294ac4ef58cd00db14729f#diff-9bef9b77373e93c42e9a143e5cf7d018), and [Commit C](https://github.com/dke-chan/ascr/commit/9df438fb313a39e6f84cf0e702f3c3a8255d3b1c#diff-9bef9b77373e93c42e9a143e5cf7d018). 

The key things that need to be included in the **ascr** model object are the following:

- The GAMs smoothers
- Whether the covariates were scaled or not

These components allow us to use `mgcv::PredictMat` for the GAMs to construct the model matrix given the fitted model for new covariate values.

Currently, I'm fairly certain that I've managed to get numeric explanatory variables and GAM smooths of numeric explanatory variables working in the commit linked above. Categorical//factor variables won't work with my current implementation, interactions between variables, and contrasts (ie. polynomial contrasts).

**Comment by b-steve** [comment]
Just trying to figure out whether or not this has been sorted. At the moment `locations()` works simply by using the component `D.mask` of the fitted model object, but this only works when the same mask used to fit the model is also used for the plotting. By "recalculate" do you mean, for example, allowing the user to pass their own finer mask to locations()?

**Comment by dke-chan** [comment]
Yes! I meant that the user can pass their own finer mask to locations().

**Comment by b-steve** [comment]
Did you get something working that would do the trick in general (i.e., for factors, interactions, and sno on)? If so, feel free to send a pull request. If not, no problem: in this commit [4a0d7433e0b23ff40ebb856ba6108256424ffb9f] I added a predict method to calculate the estimated density at a new mask point given its covariates, which I think will make it easy enough to get `locations()` working with new mask points and covariate values.

**Comment by b-steve** [comment]
This should be working now. I tested with interacting factors and everything looked good.

**Comment by dke-chan** [comment]
Alright! I'll look into it when I review my code to work on the latest package version.
