### ISSUE TITLE
Rewording suggestion for help file

### ISSUE THREAD

**Issue by david-borchers** [b-steve/ascr#17]
The help for create.capt currently says this under "Details":

"Additional optional columns can specify the additional information collected over the course of the survey:
A column named bearing containing estimated bearings from which the detector detected the individual."

I found the last sentence a little confusing. This might be clearer?: 
"A column named bearing containing estimated bearings from the detector to each detected individual."

(Now really nit-picking: because you might get multiple detections from the same individual, and different rows of the capture file might be different sounds from the same individual, shouldn't you really say "sound or individual" here, instead of "individual" - and also elsewhere in the help files?)

**Comment by b-steve** [comment]
Thanks, David, good suggestions. A lot of the documentation was written quite a few years ago and could probably do with a bit of an overhaul. I suspect a lot of it isn't read by anyone other than me, so feel free to keep posting if you find things confusing or incorrect.
