### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kieranyes** [b-steve/ascr#19]
Hi, had been using this recently but had to reinstall. The installation script does not appear to be working. I welcome any advice on this issue.

(previous parts worked)

download(bin.name, destfile = dest)
trying URL 'https://github.com/b-steve/ascr/releases/download/v2.2.2/ascr_2.2.2.zip'
**Error in download.file(url, method = method, ...) : 
  cannot open URL 'https://github.com/b-steve/ascr/releases/download/v2.2.2/ascr_2.2.2.zip'**
 install.packages(dest, repos = NULL, type = type)
Installing package into ‘C:/Users/Kieran/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error in install.packages : zip file ‘ascr_2.2.2.zip’ not found
 unlink(dest)

**Comment by b-steve** [comment]
Sorry, you caught me midway through releasing a new version. Try again now.
