### ISSUE TITLE
folder nesting during bootstrap

### ISSUE THREAD

**Issue by dill** [b-steve/ascr#3]
Strange issue I've come across running many bootstraps is that the `ascr<jumble of letters and numbers>` folders tend to nest inside of one another. Seems like it would be better to create a `ascr-bootstraps-<jumble>` folder and put all of the bootstraps in there rather than this weird nesting thing.

Related: if the bootstrap fails, you end up with your R session burried deep in this nested directory structure. Probably need to add an `on.exit` call to the end of the bootstrap function so you end up back somewhere sensible if everything goes wrong.

(Sorry I've not tried to patch this as I don't want to think about RCpp at the moment.)

Can provide an example via e-mail if that's useful!

**Comment by b-steve** [comment]
Ach, yes, this is a bit messy. Whenever you fit a model with fit.ascr()
(which is called by the bootstrap function), a "temporary" folder named
"ascr<jumble>" will be created. A symbolic link to the ADMB executable
sitting in the package directory is put inside the temporary folder, along
with all the bits and pieces needed by ADMB to maximise the likelihood.
ADMB then runs inside the "temporary" folder. The reason each model fit
gets its own directory is that ADMB doesn't work if you try to fit multiple
models in the same working directory. You may end up fitting multiple
models at once, for example, if you are running things in parallel within
the bootstrap function, or with par.fit.ascr(), or even if you are doing
something rudimentary like opening two R sessions and independently fitting
models in them. The temporary directory is supposed to be deleted after the
model has been fitted. The reason for the jumble of letters is to avoid two
directories being created with the same name and overwriting one another.

I think this problem occurs when a model fit fails. A "temporary" directory
is created. R moves into the temporary directory. An error gets thrown and
R never moves back out of it or deletes it. R then moves onto the next
iteration of the bootstrap (for example) and creates a new "temporary"
directory is created inside the other one. Rinse and repeat. You find
yourself buried within a labyrinth of not-so-temporary directories.

I'll have a look into this sometime soon to figure out a neater way...

**Comment by dill** [comment]
Ah okay, that makes sense, I think I'm dropping a fair number of reps, 
so that explains why there aren't 10s of 1000s of directories (just "lots").

This is not really a problem but can make it hard to work out where 
stuff gets saved if your session crashes and you're keeping intermediate 
output.

**Comment by b-steve** [comment]
Easy fix once I found `on.exit()`; temporary directories are now deleted even if `fit.ascr()` hits an error.

**Comment by b-steve** [comment]
Oh Dave even told me about `on.exit()` when he made this issue but I ignored it.
